// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"context"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// ManagersGet invokes GET /managers operation.
	//
	// Возвращает список всех менеджеров задач сервера.
	//
	// GET /managers
	ManagersGet(ctx context.Context) (ManagersGetRes, error)
	// ManagersManagerNameTasksContractNameDelete invokes DELETE /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Удаляет все файлы задачи вместе с папкой.
	//
	// DELETE /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameDeleteParams) (ManagersManagerNameTasksContractNameDeleteRes, error)
	// ManagersManagerNameTasksContractNameFilenameDelete invokes DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Удаляет файл с переданным именем из папки задачи.
	//
	// DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameDeleteParams) (ManagersManagerNameTasksContractNameFilenameDeleteRes, error)
	// ManagersManagerNameTasksContractNameFilenameGet invokes GET /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Возвращает файл с соответствующим названием из папки
	// задания.
	//
	// GET /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenameGet(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameGetParams) (ManagersManagerNameTasksContractNameFilenameGetRes, error)
	// ManagersManagerNameTasksContractNameFilenamePost invokes POST /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Загрузка файла в папку задачи.
	//
	// POST /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenamePost(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePostReq, params ManagersManagerNameTasksContractNameFilenamePostParams) (ManagersManagerNameTasksContractNameFilenamePostRes, error)
	// ManagersManagerNameTasksContractNameFilenamePut invokes PUT /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Загрузка файла в папку задачи. Заменяет существующий
	// файл.
	//
	// PUT /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenamePut(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePutReq, params ManagersManagerNameTasksContractNameFilenamePutParams) (ManagersManagerNameTasksContractNameFilenamePutRes, error)
	// ManagersManagerNameTasksContractNameGet invokes GET /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Возвращает объект задачи вместе со списком файлов.
	//
	// GET /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNameGet(ctx context.Context, params ManagersManagerNameTasksContractNameGetParams) (ManagersManagerNameTasksContractNameGetRes, error)
	// ManagersManagerNameTasksContractNamePatch invokes PATCH /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Обновляет одно или несколько полей задачи.
	//
	// PATCH /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNamePatch(ctx context.Context, request *TaskUpdate, params ManagersManagerNameTasksContractNamePatchParams) (ManagersManagerNameTasksContractNamePatchRes, error)
	// ManagersManagerNameTasksGet invokes GET /managers/{managerName}/tasks operation.
	//
	// Возвращает список задач менеджера.
	//
	// GET /managers/{managerName}/tasks
	ManagersManagerNameTasksGet(ctx context.Context, params ManagersManagerNameTasksGetParams) (ManagersManagerNameTasksGetRes, error)
	// ManagersManagerNameTasksPost invokes POST /managers/{managerName}/tasks operation.
	//
	// Создаёт новую активную задачу в менеджере задач.
	//
	// POST /managers/{managerName}/tasks
	ManagersManagerNameTasksPost(ctx context.Context, request *TaskCreateMultipart, params ManagersManagerNameTasksPostParams) (ManagersManagerNameTasksPostRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// ManagersGet invokes GET /managers operation.
//
// Возвращает список всех менеджеров задач сервера.
//
// GET /managers
func (c *Client) ManagersGet(ctx context.Context) (ManagersGetRes, error) {
	res, err := c.sendManagersGet(ctx)
	return res, err
}

func (c *Client) sendManagersGet(ctx context.Context) (res ManagersGetRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/managers"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersGetOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/managers"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameDelete invokes DELETE /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Удаляет все файлы задачи вместе с папкой.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}
func (c *Client) ManagersManagerNameTasksContractNameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameDeleteParams) (ManagersManagerNameTasksContractNameDeleteRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameDelete(ctx, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameDeleteParams) (res ManagersManagerNameTasksContractNameDeleteRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameDeleteOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [6]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameFilenameDelete invokes DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Удаляет файл с переданным именем из папки задачи.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (c *Client) ManagersManagerNameTasksContractNameFilenameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameDeleteParams) (ManagersManagerNameTasksContractNameFilenameDeleteRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameFilenameDelete(ctx, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameFilenameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameDeleteParams) (res ManagersManagerNameTasksContractNameFilenameDeleteRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("DELETE"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}/{filename}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameFilenameDeleteOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [8]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	pathParts[6] = "/"
	{
		// Encode "filename" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "filename",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Filename))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[7] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "DELETE", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameFilenameDeleteResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameFilenameGet invokes GET /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Возвращает файл с соответствующим названием из папки
// задания.
//
// GET /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (c *Client) ManagersManagerNameTasksContractNameFilenameGet(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameGetParams) (ManagersManagerNameTasksContractNameFilenameGetRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameFilenameGet(ctx, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameFilenameGet(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameGetParams) (res ManagersManagerNameTasksContractNameFilenameGetRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}/{filename}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameFilenameGetOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [8]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	pathParts[6] = "/"
	{
		// Encode "filename" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "filename",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Filename))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[7] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameFilenameGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameFilenamePost invokes POST /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Загрузка файла в папку задачи.
//
// POST /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (c *Client) ManagersManagerNameTasksContractNameFilenamePost(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePostReq, params ManagersManagerNameTasksContractNameFilenamePostParams) (ManagersManagerNameTasksContractNameFilenamePostRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameFilenamePost(ctx, request, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameFilenamePost(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePostReq, params ManagersManagerNameTasksContractNameFilenamePostParams) (res ManagersManagerNameTasksContractNameFilenamePostRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}/{filename}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameFilenamePostOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [8]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	pathParts[6] = "/"
	{
		// Encode "filename" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "filename",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Filename))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[7] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeManagersManagerNameTasksContractNameFilenamePostRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameFilenamePostResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameFilenamePut invokes PUT /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Загрузка файла в папку задачи. Заменяет существующий
// файл.
//
// PUT /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (c *Client) ManagersManagerNameTasksContractNameFilenamePut(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePutReq, params ManagersManagerNameTasksContractNameFilenamePutParams) (ManagersManagerNameTasksContractNameFilenamePutRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameFilenamePut(ctx, request, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameFilenamePut(ctx context.Context, request ManagersManagerNameTasksContractNameFilenamePutReq, params ManagersManagerNameTasksContractNameFilenamePutParams) (res ManagersManagerNameTasksContractNameFilenamePutRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("PUT"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}/{filename}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameFilenamePutOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [8]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	pathParts[6] = "/"
	{
		// Encode "filename" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "filename",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Filename))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[7] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PUT", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeManagersManagerNameTasksContractNameFilenamePutRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameFilenamePutResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNameGet invokes GET /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Возвращает объект задачи вместе со списком файлов.
//
// GET /managers/{managerName}/tasks/{contract}/{name}
func (c *Client) ManagersManagerNameTasksContractNameGet(ctx context.Context, params ManagersManagerNameTasksContractNameGetParams) (ManagersManagerNameTasksContractNameGetRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNameGet(ctx, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNameGet(ctx context.Context, params ManagersManagerNameTasksContractNameGetParams) (res ManagersManagerNameTasksContractNameGetRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNameGetOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [6]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNameGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksContractNamePatch invokes PATCH /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Обновляет одно или несколько полей задачи.
//
// PATCH /managers/{managerName}/tasks/{contract}/{name}
func (c *Client) ManagersManagerNameTasksContractNamePatch(ctx context.Context, request *TaskUpdate, params ManagersManagerNameTasksContractNamePatchParams) (ManagersManagerNameTasksContractNamePatchRes, error) {
	res, err := c.sendManagersManagerNameTasksContractNamePatch(ctx, request, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksContractNamePatch(ctx context.Context, request *TaskUpdate, params ManagersManagerNameTasksContractNamePatchParams) (res ManagersManagerNameTasksContractNamePatchRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("PATCH"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks/{contract}/{name}"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksContractNamePatchOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [6]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks/"
	{
		// Encode "contract" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "contract",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Contract))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[3] = encoded
	}
	pathParts[4] = "/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[5] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "PATCH", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeManagersManagerNameTasksContractNamePatchRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksContractNamePatchResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksGet invokes GET /managers/{managerName}/tasks operation.
//
// Возвращает список задач менеджера.
//
// GET /managers/{managerName}/tasks
func (c *Client) ManagersManagerNameTasksGet(ctx context.Context, params ManagersManagerNameTasksGetParams) (ManagersManagerNameTasksGetRes, error) {
	res, err := c.sendManagersManagerNameTasksGet(ctx, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksGet(ctx context.Context, params ManagersManagerNameTasksGetParams) (res ManagersManagerNameTasksGetRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("GET"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksGetOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeQueryParams"
	q := uri.NewQueryEncoder()
	{
		// Encode "contract" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "contract",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Contract.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "status" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "status",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Status.Get(); ok {
				return e.EncodeValue(conv.StringToString(string(val)))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksGetResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ManagersManagerNameTasksPost invokes POST /managers/{managerName}/tasks operation.
//
// Создаёт новую активную задачу в менеджере задач.
//
// POST /managers/{managerName}/tasks
func (c *Client) ManagersManagerNameTasksPost(ctx context.Context, request *TaskCreateMultipart, params ManagersManagerNameTasksPostParams) (ManagersManagerNameTasksPostRes, error) {
	res, err := c.sendManagersManagerNameTasksPost(ctx, request, params)
	return res, err
}

func (c *Client) sendManagersManagerNameTasksPost(ctx context.Context, request *TaskCreateMultipart, params ManagersManagerNameTasksPostParams) (res ManagersManagerNameTasksPostRes, err error) {
	otelAttrs := []attribute.KeyValue{
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/managers/{managerName}/tasks"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, ManagersManagerNameTasksPostOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/managers/"
	{
		// Encode "managerName" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "managerName",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.ManagerName))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/tasks"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeManagersManagerNameTasksPostRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer body.Close()

	stage = "DecodeResponse"
	result, err := decodeManagersManagerNameTasksPostResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
