// Code generated by ogen, DO NOT EDIT.

package api_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	ManagersGetOperation                                        OperationName = "ManagersGet"
	ManagersManagerNameTasksContractNameDeleteOperation         OperationName = "ManagersManagerNameTasksContractNameDelete"
	ManagersManagerNameTasksContractNameFilenameDeleteOperation OperationName = "ManagersManagerNameTasksContractNameFilenameDelete"
	ManagersManagerNameTasksContractNameFilenameGetOperation    OperationName = "ManagersManagerNameTasksContractNameFilenameGet"
	ManagersManagerNameTasksContractNameFilenamePostOperation   OperationName = "ManagersManagerNameTasksContractNameFilenamePost"
	ManagersManagerNameTasksContractNameFilenamePutOperation    OperationName = "ManagersManagerNameTasksContractNameFilenamePut"
	ManagersManagerNameTasksContractNameGetOperation            OperationName = "ManagersManagerNameTasksContractNameGet"
	ManagersManagerNameTasksContractNamePatchOperation          OperationName = "ManagersManagerNameTasksContractNamePatch"
	ManagersManagerNameTasksGetOperation                        OperationName = "ManagersManagerNameTasksGet"
	ManagersManagerNameTasksPostOperation                       OperationName = "ManagersManagerNameTasksPost"
)
