// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"fmt"
	"io"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	ht "github.com/ogen-go/ogen/http"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Сообщение об ошибке.
// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Код ошибки.
	Code ErrorResponseCode `json:"code"`
	// Текст ошибки.
	Message string `json:"message"`
	// HTTP статус-код ошибки.
	Status int `json:"status"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() ErrorResponseCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// GetStatus returns the value of Status.
func (s *ErrorResponse) GetStatus() int {
	return s.Status
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val ErrorResponseCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// SetStatus sets the value of Status.
func (s *ErrorResponse) SetStatus(val int) {
	s.Status = val
}

func (*ErrorResponse) managersGetRes() {}

// Код ошибки.
type ErrorResponseCode string

const (
	ErrorResponseCodeBADREQUEST    ErrorResponseCode = "BAD_REQUEST"
	ErrorResponseCodeNOTFOUND      ErrorResponseCode = "NOT_FOUND"
	ErrorResponseCodeCONFLICT      ErrorResponseCode = "CONFLICT"
	ErrorResponseCodeINTERNALERROR ErrorResponseCode = "INTERNAL_ERROR"
)

// AllValues returns all ErrorResponseCode values.
func (ErrorResponseCode) AllValues() []ErrorResponseCode {
	return []ErrorResponseCode{
		ErrorResponseCodeBADREQUEST,
		ErrorResponseCodeNOTFOUND,
		ErrorResponseCodeCONFLICT,
		ErrorResponseCodeINTERNALERROR,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ErrorResponseCode) MarshalText() ([]byte, error) {
	switch s {
	case ErrorResponseCodeBADREQUEST:
		return []byte(s), nil
	case ErrorResponseCodeNOTFOUND:
		return []byte(s), nil
	case ErrorResponseCodeCONFLICT:
		return []byte(s), nil
	case ErrorResponseCodeINTERNALERROR:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ErrorResponseCode) UnmarshalText(data []byte) error {
	switch ErrorResponseCode(data) {
	case ErrorResponseCodeBADREQUEST:
		*s = ErrorResponseCodeBADREQUEST
		return nil
	case ErrorResponseCodeNOTFOUND:
		*s = ErrorResponseCodeNOTFOUND
		return nil
	case ErrorResponseCodeCONFLICT:
		*s = ErrorResponseCodeCONFLICT
		return nil
	case ErrorResponseCodeINTERNALERROR:
		*s = ErrorResponseCodeINTERNALERROR
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// ErrorStatusCode wraps ErrorResponse with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

type Files []string

func (*Files) managersManagerNameTasksContractNameFilenamePostRes() {}
func (*Files) managersManagerNameTasksContractNameFilenamePutRes()  {}

// Менеджер задач.
// Ref: #/components/schemas/Manager
type Manager struct {
	// Адресное имя менеджера.
	Name string `json:"name"`
	// Отображаемое имя менеджера.
	DisplayName string `json:"display_name"`
}

// GetName returns the value of Name.
func (s *Manager) GetName() string {
	return s.Name
}

// GetDisplayName returns the value of DisplayName.
func (s *Manager) GetDisplayName() string {
	return s.DisplayName
}

// SetName sets the value of Name.
func (s *Manager) SetName(val string) {
	s.Name = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Manager) SetDisplayName(val string) {
	s.DisplayName = val
}

type Managers []Manager

func (*Managers) managersGetRes() {}

type ManagersManagerNameTasksContractNameDeleteInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameDeleteInternalServerError) managersManagerNameTasksContractNameDeleteRes() {
}

// ManagersManagerNameTasksContractNameDeleteNoContent is response for ManagersManagerNameTasksContractNameDelete operation.
type ManagersManagerNameTasksContractNameDeleteNoContent struct{}

func (*ManagersManagerNameTasksContractNameDeleteNoContent) managersManagerNameTasksContractNameDeleteRes() {
}

type ManagersManagerNameTasksContractNameDeleteNotFound ErrorResponse

func (*ManagersManagerNameTasksContractNameDeleteNotFound) managersManagerNameTasksContractNameDeleteRes() {
}

type ManagersManagerNameTasksContractNameFilenameDeleteInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenameDeleteInternalServerError) managersManagerNameTasksContractNameFilenameDeleteRes() {
}

// ManagersManagerNameTasksContractNameFilenameDeleteNoContent is response for ManagersManagerNameTasksContractNameFilenameDelete operation.
type ManagersManagerNameTasksContractNameFilenameDeleteNoContent struct{}

func (*ManagersManagerNameTasksContractNameFilenameDeleteNoContent) managersManagerNameTasksContractNameFilenameDeleteRes() {
}

type ManagersManagerNameTasksContractNameFilenameDeleteNotFound ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenameDeleteNotFound) managersManagerNameTasksContractNameFilenameDeleteRes() {
}

type ManagersManagerNameTasksContractNameFilenameGetInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenameGetInternalServerError) managersManagerNameTasksContractNameFilenameGetRes() {
}

type ManagersManagerNameTasksContractNameFilenameGetNotFound ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenameGetNotFound) managersManagerNameTasksContractNameFilenameGetRes() {
}

type ManagersManagerNameTasksContractNameFilenameGetOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ManagersManagerNameTasksContractNameFilenameGetOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*ManagersManagerNameTasksContractNameFilenameGetOK) managersManagerNameTasksContractNameFilenameGetRes() {
}

type ManagersManagerNameTasksContractNameFilenamePostBadRequest ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenamePostBadRequest) managersManagerNameTasksContractNameFilenamePostRes() {
}

type ManagersManagerNameTasksContractNameFilenamePostConflict ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenamePostConflict) managersManagerNameTasksContractNameFilenamePostRes() {
}

type ManagersManagerNameTasksContractNameFilenamePostInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenamePostInternalServerError) managersManagerNameTasksContractNameFilenamePostRes() {
}

type ManagersManagerNameTasksContractNameFilenamePostReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ManagersManagerNameTasksContractNameFilenamePostReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type ManagersManagerNameTasksContractNameFilenamePutBadRequest ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenamePutBadRequest) managersManagerNameTasksContractNameFilenamePutRes() {
}

type ManagersManagerNameTasksContractNameFilenamePutInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameFilenamePutInternalServerError) managersManagerNameTasksContractNameFilenamePutRes() {
}

type ManagersManagerNameTasksContractNameFilenamePutReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s ManagersManagerNameTasksContractNameFilenamePutReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type ManagersManagerNameTasksContractNameGetInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNameGetInternalServerError) managersManagerNameTasksContractNameGetRes() {
}

type ManagersManagerNameTasksContractNameGetNotFound ErrorResponse

func (*ManagersManagerNameTasksContractNameGetNotFound) managersManagerNameTasksContractNameGetRes() {
}

type ManagersManagerNameTasksContractNamePatchBadRequest ErrorResponse

func (*ManagersManagerNameTasksContractNamePatchBadRequest) managersManagerNameTasksContractNamePatchRes() {
}

type ManagersManagerNameTasksContractNamePatchConflict ErrorResponse

func (*ManagersManagerNameTasksContractNamePatchConflict) managersManagerNameTasksContractNamePatchRes() {
}

type ManagersManagerNameTasksContractNamePatchInternalServerError ErrorResponse

func (*ManagersManagerNameTasksContractNamePatchInternalServerError) managersManagerNameTasksContractNamePatchRes() {
}

type ManagersManagerNameTasksContractNamePatchNotFound ErrorResponse

func (*ManagersManagerNameTasksContractNamePatchNotFound) managersManagerNameTasksContractNamePatchRes() {
}

type ManagersManagerNameTasksGetBadRequest ErrorResponse

func (*ManagersManagerNameTasksGetBadRequest) managersManagerNameTasksGetRes() {}

type ManagersManagerNameTasksGetInternalServerError ErrorResponse

func (*ManagersManagerNameTasksGetInternalServerError) managersManagerNameTasksGetRes() {}

type ManagersManagerNameTasksGetNotFound ErrorResponse

func (*ManagersManagerNameTasksGetNotFound) managersManagerNameTasksGetRes() {}

type ManagersManagerNameTasksGetStatus string

const (
	ManagersManagerNameTasksGetStatusActive    ManagersManagerNameTasksGetStatus = "active"
	ManagersManagerNameTasksGetStatusCompleted ManagersManagerNameTasksGetStatus = "completed"
)

// AllValues returns all ManagersManagerNameTasksGetStatus values.
func (ManagersManagerNameTasksGetStatus) AllValues() []ManagersManagerNameTasksGetStatus {
	return []ManagersManagerNameTasksGetStatus{
		ManagersManagerNameTasksGetStatusActive,
		ManagersManagerNameTasksGetStatusCompleted,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ManagersManagerNameTasksGetStatus) MarshalText() ([]byte, error) {
	switch s {
	case ManagersManagerNameTasksGetStatusActive:
		return []byte(s), nil
	case ManagersManagerNameTasksGetStatusCompleted:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ManagersManagerNameTasksGetStatus) UnmarshalText(data []byte) error {
	switch ManagersManagerNameTasksGetStatus(data) {
	case ManagersManagerNameTasksGetStatusActive:
		*s = ManagersManagerNameTasksGetStatusActive
		return nil
	case ManagersManagerNameTasksGetStatusCompleted:
		*s = ManagersManagerNameTasksGetStatusCompleted
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ManagersManagerNameTasksPostBadRequest ErrorResponse

func (*ManagersManagerNameTasksPostBadRequest) managersManagerNameTasksPostRes() {}

type ManagersManagerNameTasksPostConflict ErrorResponse

func (*ManagersManagerNameTasksPostConflict) managersManagerNameTasksPostRes() {}

type ManagersManagerNameTasksPostInternalServerError ErrorResponse

func (*ManagersManagerNameTasksPostInternalServerError) managersManagerNameTasksPostRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptManagersManagerNameTasksGetStatus returns new OptManagersManagerNameTasksGetStatus with value set to v.
func NewOptManagersManagerNameTasksGetStatus(v ManagersManagerNameTasksGetStatus) OptManagersManagerNameTasksGetStatus {
	return OptManagersManagerNameTasksGetStatus{
		Value: v,
		Set:   true,
	}
}

// OptManagersManagerNameTasksGetStatus is optional ManagersManagerNameTasksGetStatus.
type OptManagersManagerNameTasksGetStatus struct {
	Value ManagersManagerNameTasksGetStatus
	Set   bool
}

// IsSet returns true if OptManagersManagerNameTasksGetStatus was set.
func (o OptManagersManagerNameTasksGetStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptManagersManagerNameTasksGetStatus) Reset() {
	var v ManagersManagerNameTasksGetStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptManagersManagerNameTasksGetStatus) SetTo(v ManagersManagerNameTasksGetStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptManagersManagerNameTasksGetStatus) Get() (v ManagersManagerNameTasksGetStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptManagersManagerNameTasksGetStatus) Or(d ManagersManagerNameTasksGetStatus) ManagersManagerNameTasksGetStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Задача.
// Ref: #/components/schemas/Task
type Task struct {
	// Договор.
	Contract string `json:"contract"`
	// Имя задания.
	Name string `json:"name"`
	// Статус задания.
	Completed bool `json:"completed"`
	// Время последнего обновления.
	Updated time.Time `json:"updated"`
}

// GetContract returns the value of Contract.
func (s *Task) GetContract() string {
	return s.Contract
}

// GetName returns the value of Name.
func (s *Task) GetName() string {
	return s.Name
}

// GetCompleted returns the value of Completed.
func (s *Task) GetCompleted() bool {
	return s.Completed
}

// GetUpdated returns the value of Updated.
func (s *Task) GetUpdated() time.Time {
	return s.Updated
}

// SetContract sets the value of Contract.
func (s *Task) SetContract(val string) {
	s.Contract = val
}

// SetName sets the value of Name.
func (s *Task) SetName(val string) {
	s.Name = val
}

// SetCompleted sets the value of Completed.
func (s *Task) SetCompleted(val bool) {
	s.Completed = val
}

// SetUpdated sets the value of Updated.
func (s *Task) SetUpdated(val time.Time) {
	s.Updated = val
}

// Ref: #/components/schemas/TaskCreate
type TaskCreateMultipart struct {
	// Номер договора.
	Contract string `json:"contract"`
	// Имя задачи.
	Name string `json:"name"`
	// Файлы задачи.
	Files []ht.MultipartFile `json:"files"`
}

// GetContract returns the value of Contract.
func (s *TaskCreateMultipart) GetContract() string {
	return s.Contract
}

// GetName returns the value of Name.
func (s *TaskCreateMultipart) GetName() string {
	return s.Name
}

// GetFiles returns the value of Files.
func (s *TaskCreateMultipart) GetFiles() []ht.MultipartFile {
	return s.Files
}

// SetContract sets the value of Contract.
func (s *TaskCreateMultipart) SetContract(val string) {
	s.Contract = val
}

// SetName sets the value of Name.
func (s *TaskCreateMultipart) SetName(val string) {
	s.Name = val
}

// SetFiles sets the value of Files.
func (s *TaskCreateMultipart) SetFiles(val []ht.MultipartFile) {
	s.Files = val
}

// Ref: #/components/schemas/TaskUpdate
type TaskUpdate struct {
	// Статус задачи.
	Completed OptBool `json:"completed"`
	// Имя задачи.
	Name OptString `json:"name"`
	// Договор задачи.
	Contract OptString `json:"contract"`
}

// GetCompleted returns the value of Completed.
func (s *TaskUpdate) GetCompleted() OptBool {
	return s.Completed
}

// GetName returns the value of Name.
func (s *TaskUpdate) GetName() OptString {
	return s.Name
}

// GetContract returns the value of Contract.
func (s *TaskUpdate) GetContract() OptString {
	return s.Contract
}

// SetCompleted sets the value of Completed.
func (s *TaskUpdate) SetCompleted(val OptBool) {
	s.Completed = val
}

// SetName sets the value of Name.
func (s *TaskUpdate) SetName(val OptString) {
	s.Name = val
}

// SetContract sets the value of Contract.
func (s *TaskUpdate) SetContract(val OptString) {
	s.Contract = val
}

// Merged schema.
// Ref: #/components/schemas/TaskWithFiles
type TaskWithFiles struct {
	// Договор.
	Contract string `json:"contract"`
	// Имя задания.
	Name string `json:"name"`
	// Статус задания.
	Completed bool `json:"completed"`
	// Время последнего обновления.
	Updated time.Time `json:"updated"`
	Files   Files     `json:"files"`
}

// GetContract returns the value of Contract.
func (s *TaskWithFiles) GetContract() string {
	return s.Contract
}

// GetName returns the value of Name.
func (s *TaskWithFiles) GetName() string {
	return s.Name
}

// GetCompleted returns the value of Completed.
func (s *TaskWithFiles) GetCompleted() bool {
	return s.Completed
}

// GetUpdated returns the value of Updated.
func (s *TaskWithFiles) GetUpdated() time.Time {
	return s.Updated
}

// GetFiles returns the value of Files.
func (s *TaskWithFiles) GetFiles() Files {
	return s.Files
}

// SetContract sets the value of Contract.
func (s *TaskWithFiles) SetContract(val string) {
	s.Contract = val
}

// SetName sets the value of Name.
func (s *TaskWithFiles) SetName(val string) {
	s.Name = val
}

// SetCompleted sets the value of Completed.
func (s *TaskWithFiles) SetCompleted(val bool) {
	s.Completed = val
}

// SetUpdated sets the value of Updated.
func (s *TaskWithFiles) SetUpdated(val time.Time) {
	s.Updated = val
}

// SetFiles sets the value of Files.
func (s *TaskWithFiles) SetFiles(val Files) {
	s.Files = val
}

func (*TaskWithFiles) managersManagerNameTasksContractNameGetRes()   {}
func (*TaskWithFiles) managersManagerNameTasksContractNamePatchRes() {}

// TaskWithFilesHeaders wraps TaskWithFiles with response headers.
type TaskWithFilesHeaders struct {
	Location OptURI
	Response TaskWithFiles
}

// GetLocation returns the value of Location.
func (s *TaskWithFilesHeaders) GetLocation() OptURI {
	return s.Location
}

// GetResponse returns the value of Response.
func (s *TaskWithFilesHeaders) GetResponse() TaskWithFiles {
	return s.Response
}

// SetLocation sets the value of Location.
func (s *TaskWithFilesHeaders) SetLocation(val OptURI) {
	s.Location = val
}

// SetResponse sets the value of Response.
func (s *TaskWithFilesHeaders) SetResponse(val TaskWithFiles) {
	s.Response = val
}

func (*TaskWithFilesHeaders) managersManagerNameTasksPostRes() {}

type Tasks []Task

func (*Tasks) managersManagerNameTasksGetRes() {}
