// Code generated by ogen, DO NOT EDIT.
package api_v1

type ManagersGetRes interface {
	managersGetRes()
}

type ManagersManagerNameTasksContractNameDeleteRes interface {
	managersManagerNameTasksContractNameDeleteRes()
}

type ManagersManagerNameTasksContractNameFilenameDeleteRes interface {
	managersManagerNameTasksContractNameFilenameDeleteRes()
}

type ManagersManagerNameTasksContractNameFilenameGetRes interface {
	managersManagerNameTasksContractNameFilenameGetRes()
}

type ManagersManagerNameTasksContractNameFilenamePostRes interface {
	managersManagerNameTasksContractNameFilenamePostRes()
}

type ManagersManagerNameTasksContractNameFilenamePutRes interface {
	managersManagerNameTasksContractNameFilenamePutRes()
}

type ManagersManagerNameTasksContractNameGetRes interface {
	managersManagerNameTasksContractNameGetRes()
}

type ManagersManagerNameTasksContractNamePatchRes interface {
	managersManagerNameTasksContractNamePatchRes()
}

type ManagersManagerNameTasksGetRes interface {
	managersManagerNameTasksGetRes()
}

type ManagersManagerNameTasksPostRes interface {
	managersManagerNameTasksPostRes()
}
