// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *ErrorResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Code.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ErrorResponseCode) Validate() error {
	switch s {
	case "BAD_REQUEST":
		return nil
	case "NOT_FOUND":
		return nil
	case "CONFLICT":
		return nil
	case "INTERNAL_ERROR":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *ErrorStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s Files) Validate() error {
	alias := ([]string)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s Managers) Validate() error {
	alias := ([]Manager)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s *TaskDeleteBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskDeleteInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskDeleteNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileDeleteBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileDeleteInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileDeleteNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileGetBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileGetInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFileGetNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFilePostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFilePostConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFilePostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFilePutBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskFilePutInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskGetBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskGetInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskGetNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPatchBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPatchConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPatchInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPatchNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPostBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPostConflict) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskPostInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TaskWithFiles) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Files.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "files",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *TaskWithFilesHeaders) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s Tasks) Validate() error {
	alias := ([]Task)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s *TasksGetBadRequest) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TasksGetInternalServerError) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *TasksGetNotFound) Validate() error {
	alias := (*ErrorResponse)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s TasksGetStatus) Validate() error {
	switch s {
	case "active":
		return nil
	case "completed":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
