// Code generated by ogen, DO NOT EDIT.

package api_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	ManagersGetOperation    OperationName = "ManagersGet"
	TaskDeleteOperation     OperationName = "TaskDelete"
	TaskFileDeleteOperation OperationName = "TaskFileDelete"
	TaskFileGetOperation    OperationName = "TaskFileGet"
	TaskFilePostOperation   OperationName = "TaskFilePost"
	TaskFilePutOperation    OperationName = "TaskFilePut"
	TaskGetOperation        OperationName = "TaskGet"
	TaskPatchOperation      OperationName = "TaskPatch"
	TaskPostOperation       OperationName = "TaskPost"
	TasksGetOperation       OperationName = "TasksGet"
)
