// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ManagersGet implements GET /managers operation.
	//
	// Возвращает список всех менеджеров задач сервера.
	//
	// GET /managers
	ManagersGet(ctx context.Context) (ManagersGetRes, error)
	// ManagersManagerNameTasksContractNameDelete implements DELETE /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Удаляет все файлы задачи вместе с папкой.
	//
	// DELETE /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameDeleteParams) (ManagersManagerNameTasksContractNameDeleteRes, error)
	// ManagersManagerNameTasksContractNameFilenameDelete implements DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Удаляет файл с переданным именем из папки задачи.
	//
	// DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameDeleteParams) (ManagersManagerNameTasksContractNameFilenameDeleteRes, error)
	// ManagersManagerNameTasksContractNameFilenameGet implements GET /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Возвращает файл с соответствующим названием из папки
	// задания.
	//
	// GET /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenameGet(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameGetParams) (ManagersManagerNameTasksContractNameFilenameGetRes, error)
	// ManagersManagerNameTasksContractNameFilenamePost implements POST /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Загрузка файла в папку задачи.
	//
	// POST /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenamePost(ctx context.Context, req ManagersManagerNameTasksContractNameFilenamePostReq, params ManagersManagerNameTasksContractNameFilenamePostParams) (ManagersManagerNameTasksContractNameFilenamePostRes, error)
	// ManagersManagerNameTasksContractNameFilenamePut implements PUT /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
	//
	// Загрузка файла в папку задачи. Заменяет существующий
	// файл.
	//
	// PUT /managers/{managerName}/tasks/{contract}/{name}/{filename}
	ManagersManagerNameTasksContractNameFilenamePut(ctx context.Context, req ManagersManagerNameTasksContractNameFilenamePutReq, params ManagersManagerNameTasksContractNameFilenamePutParams) (ManagersManagerNameTasksContractNameFilenamePutRes, error)
	// ManagersManagerNameTasksContractNameGet implements GET /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Возвращает объект задачи вместе со списком файлов.
	//
	// GET /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNameGet(ctx context.Context, params ManagersManagerNameTasksContractNameGetParams) (ManagersManagerNameTasksContractNameGetRes, error)
	// ManagersManagerNameTasksContractNamePatch implements PATCH /managers/{managerName}/tasks/{contract}/{name} operation.
	//
	// Обновляет одно или несколько полей задачи.
	//
	// PATCH /managers/{managerName}/tasks/{contract}/{name}
	ManagersManagerNameTasksContractNamePatch(ctx context.Context, req *TaskUpdate, params ManagersManagerNameTasksContractNamePatchParams) (ManagersManagerNameTasksContractNamePatchRes, error)
	// ManagersManagerNameTasksGet implements GET /managers/{managerName}/tasks operation.
	//
	// Возвращает список задач менеджера.
	//
	// GET /managers/{managerName}/tasks
	ManagersManagerNameTasksGet(ctx context.Context, params ManagersManagerNameTasksGetParams) (ManagersManagerNameTasksGetRes, error)
	// ManagersManagerNameTasksPost implements POST /managers/{managerName}/tasks operation.
	//
	// Создаёт новую активную задачу в менеджере задач.
	//
	// POST /managers/{managerName}/tasks
	ManagersManagerNameTasksPost(ctx context.Context, req *TaskCreateMultipart, params ManagersManagerNameTasksPostParams) (ManagersManagerNameTasksPostRes, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
