// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ManagersGet implements GET /managers operation.
//
// Возвращает список всех менеджеров задач сервера.
//
// GET /managers
func (UnimplementedHandler) ManagersGet(ctx context.Context) (r ManagersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameDelete implements DELETE /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Удаляет все файлы задачи вместе с папкой.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameDeleteParams) (r ManagersManagerNameTasksContractNameDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameFilenameDelete implements DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Удаляет файл с переданным именем из папки задачи.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameFilenameDelete(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameDeleteParams) (r ManagersManagerNameTasksContractNameFilenameDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameFilenameGet implements GET /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Возвращает файл с соответствующим названием из папки
// задания.
//
// GET /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameFilenameGet(ctx context.Context, params ManagersManagerNameTasksContractNameFilenameGetParams) (r ManagersManagerNameTasksContractNameFilenameGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameFilenamePost implements POST /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Загрузка файла в папку задачи.
//
// POST /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameFilenamePost(ctx context.Context, req ManagersManagerNameTasksContractNameFilenamePostReq, params ManagersManagerNameTasksContractNameFilenamePostParams) (r ManagersManagerNameTasksContractNameFilenamePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameFilenamePut implements PUT /managers/{managerName}/tasks/{contract}/{name}/{filename} operation.
//
// Загрузка файла в папку задачи. Заменяет существующий
// файл.
//
// PUT /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameFilenamePut(ctx context.Context, req ManagersManagerNameTasksContractNameFilenamePutReq, params ManagersManagerNameTasksContractNameFilenamePutParams) (r ManagersManagerNameTasksContractNameFilenamePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNameGet implements GET /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Возвращает объект задачи вместе со списком файлов.
//
// GET /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) ManagersManagerNameTasksContractNameGet(ctx context.Context, params ManagersManagerNameTasksContractNameGetParams) (r ManagersManagerNameTasksContractNameGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksContractNamePatch implements PATCH /managers/{managerName}/tasks/{contract}/{name} operation.
//
// Обновляет одно или несколько полей задачи.
//
// PATCH /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) ManagersManagerNameTasksContractNamePatch(ctx context.Context, req *TaskUpdate, params ManagersManagerNameTasksContractNamePatchParams) (r ManagersManagerNameTasksContractNamePatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksGet implements GET /managers/{managerName}/tasks operation.
//
// Возвращает список задач менеджера.
//
// GET /managers/{managerName}/tasks
func (UnimplementedHandler) ManagersManagerNameTasksGet(ctx context.Context, params ManagersManagerNameTasksGetParams) (r ManagersManagerNameTasksGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ManagersManagerNameTasksPost implements POST /managers/{managerName}/tasks operation.
//
// Создаёт новую активную задачу в менеджере задач.
//
// POST /managers/{managerName}/tasks
func (UnimplementedHandler) ManagersManagerNameTasksPost(ctx context.Context, req *TaskCreateMultipart, params ManagersManagerNameTasksPostParams) (r ManagersManagerNameTasksPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
