// Code generated by ogen, DO NOT EDIT.

package api_v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ManagersGet implements ManagersGet operation.
//
// Возвращает список всех менеджеров задач сервера.
//
// GET /managers
func (UnimplementedHandler) ManagersGet(ctx context.Context) (r ManagersGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskDelete implements TaskDelete operation.
//
// Удаляет все файлы задачи вместе с папкой.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) TaskDelete(ctx context.Context, params TaskDeleteParams) (r TaskDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskFileDelete implements TaskFileDelete operation.
//
// Удаляет файл с переданным именем из папки задачи.
//
// DELETE /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) TaskFileDelete(ctx context.Context, params TaskFileDeleteParams) (r TaskFileDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskFileGet implements TaskFileGet operation.
//
// Возвращает файл с соответствующим названием из папки
// задания.
//
// GET /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) TaskFileGet(ctx context.Context, params TaskFileGetParams) (r TaskFileGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskFilePost implements TaskFilePost operation.
//
// Загрузка файла в папку задачи.
//
// POST /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) TaskFilePost(ctx context.Context, req TaskFilePostReq, params TaskFilePostParams) (r TaskFilePostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskFilePut implements TaskFilePut operation.
//
// Загрузка файла в папку задачи. Заменяет существующий
// файл.
//
// PUT /managers/{managerName}/tasks/{contract}/{name}/{filename}
func (UnimplementedHandler) TaskFilePut(ctx context.Context, req TaskFilePutReq, params TaskFilePutParams) (r TaskFilePutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskGet implements TaskGet operation.
//
// Возвращает объект задачи вместе со списком файлов.
//
// GET /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) TaskGet(ctx context.Context, params TaskGetParams) (r TaskGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskPatch implements TaskPatch operation.
//
// Обновляет одно или несколько полей задачи.
//
// PATCH /managers/{managerName}/tasks/{contract}/{name}
func (UnimplementedHandler) TaskPatch(ctx context.Context, req *TaskUpdate, params TaskPatchParams) (r TaskPatchRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TaskPost implements TaskPost operation.
//
// Создаёт новую активную задачу в менеджере задач.
//
// POST /managers/{managerName}/tasks
func (UnimplementedHandler) TaskPost(ctx context.Context, req *TaskCreateMultipart, params TaskPostParams) (r TaskPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TasksGet implements TasksGet operation.
//
// Возвращает список задач менеджера.
//
// GET /managers/{managerName}/tasks
func (UnimplementedHandler) TasksGet(ctx context.Context, params TasksGetParams) (r TasksGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
